# This defines the style of the formatter
style = "blue"

# Stops `import` being changed to `using`
import_to_using = false
# Stops short function definitions being changed to long function definitions
short_to_long_function_def = false
# Converts ternary operators to if statements if they exceed the line length
conditional_to_if = true
# Add whitespace to type definitions.
whitespace_typedefs = true
# Enables formatting for code blocks
format_docstrings = false
# Enables formatting for markdown
format_markdown = false
# Since the `formart_markdown` can break markdown blocks in the docs, it is best to ignore
# the docs folder. 
ignore = ["docs"]
# NOTES: It is possible to skip sections of code from being formatted by typing 
# `#! format: off` and `#! format: on` comments. The same can be done for indentation with 
# `#! format: noindent`.
