name = "Mantis"
uuid = "45fd81cf-4570-4cb4-b51d-06adeaefc15d"
authors = ["Diogo Costa Cabanas <d.costacabanas@tudelft.nl>", "Joey Dekker <j.dekker-2@tudelft.nl>", "Deepesh Toshniwal <d.toshniwal@tudelft.nl>", "Artur Palha <a.palha@tudelft.nl>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeshCore = "43a99bba-f459-4d0e-8139-f3df11d847d4"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PolynomialBases = "c74db56a-226d-5e98-8bb0-a6049094aeea"
ReadVTK = "dc215faf-f008-4882-a9f7-a79a826fadc3"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
MeshCore = "1.3.5"
PolynomialBases = "0.4.21"
julia = "1.8"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ReadVTK = "dc215faf-f008-4882-a9f7-a79a826fadc3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ReadVTK", "Printf"]
