name = "Mantis"
uuid = "45fd81cf-4570-4cb4-b51d-06adeaefc15d"
authors = ["Diogo Costa Cabanas <d.costacabanas@tudelft.nl>", "Joey Dekker <j.dekker-2@tudelft.nl>", "Deepesh Toshniwal <d.toshniwal@tudelft.nl>", "Artur Palha <a.palha@tudelft.nl>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MKL_jll = "856f044c-d86e-5d09-b602-aeab76dc8ba7"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
MeshCore = "43a99bba-f459-4d0e-8139-f3df11d847d4"
PolynomialBases = "c74db56a-226d-5e98-8bb0-a6049094aeea"
ReadVTK = "dc215faf-f008-4882-a9f7-a79a826fadc3"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Subscripts = "2b7f82d5-8785-4f63-971e-f18ddbeb808e"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
MeshCore = "1.3.5"
PolynomialBases = "0.4.21"
julia = "1.9"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Printf", "Random", "Test"]
